### ISSUE TITLE
Error: During announce, bad status code 400: "com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.opentable.service.discovery.client.Announcement] value failed: null announcementId"

### ISSUE THREAD

**Issue by ArnoldZokas** [opentable/ot-discovery-nodejs#17]
I am getting this error with v0.2.0 of ot-discovery package:

```javascript
Error: During announce, bad status code 400: "com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.opentable.service.discovery.client.Announcement] value failed: null announcementId"
    at Request._callback (.../node_modules/hapi-service-discovery/node_modules/ot-discovery/discovery.js:259:10)
    at Request.self.callback (.../node_modules/hapi-service-discovery/node_modules/ot-discovery/node_modules/request/request.js:122:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (.../node_modules/hapi-service-discovery/node_modules/ot-discovery/node_modules/request/request.js:888:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (.../node_modules/hapi-service-discovery/node_modules/ot-discovery/node_modules/request/request.js:839:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)
```

looks like this was fixed in a recent commit (3f0ca707d6ea02052f5f12b50d83700a0c8c79c4), but v0.2.0 does not have this.

can you publish a new npm package?

**Comment by stevenschlansker** [comment]
Released 0.2.1

**Comment by ArnoldZokas** [comment]
thanks!

**Comment by ArnoldZokas** [comment]
Can't see 0.2.1 on NPM https://www.npmjs.com/package/ot-discovery
