### ISSUE TITLE
demo.js does not work, furthermore does not give good log messages

### ISSUE THREAD

**Issue by samsalisbury** [opentable/ot-discovery-nodejs#31]
After installing dependencies, and trying to run `node demo.js`, the following output is seen:

```
$ node demo.js                                                                  
Discovery environment 'undefined' has servers: undefined                                                              
/Users/ssalisbury/opentable/ot-discovery-nodejs/discovery.js:29                                                       
  return this.servers[Math.floor(Math.random()*this.servers.length)];                                                 
                                                           ^                                                          
TypeError: Cannot read property 'length' of undefined                                                                 
    at DiscoveryClient._randomServer (/Users/ssalisbury/opentable/ot-discovery-nodejs/discovery.js:29:60)             
    at DiscoveryClient._singleAnnounce (/Users/ssalisbury/opentable/ot-discovery-nodejs/discovery.js:244:21)          
    at DiscoveryClient.announce (/Users/ssalisbury/opentable/ot-discovery-nodejs/discovery.js:274:8)                  
    at /Users/ssalisbury/opentable/ot-discovery-nodejs/demo.js:17:9                                                   
    at Request._callback (/Users/ssalisbury/opentable/ot-discovery-nodejs/discovery.js:51:7)                          
    at self.callback (/Users/ssalisbury/opentable/ot-discovery-nodejs/node_modules/request/request.js:354:22)         
    at Request.emit (events.js:107:17)                                                                                
    at Request.onRequestError (/Users/ssalisbury/opentable/ot-discovery-nodejs/node_modules/request/request.js:1011:8)
    at ClientRequest.emit (events.js:107:17)                                                                          
    at Socket.socketErrorListener (_http_client.js:271:9)                                                                                                                                           
```

This is caused by the fact that `discovery-proxy.proxy.mesos-vpcqa.otenv.com` cannot be found. However the error message does not tell us this directly.

**Comment by stevenschlansker** [comment]
Yuck, this sucks.
